import {
  cancelGoal,
  analyseGoalRetrospective,
  applyGoalImprovement,
  approveGoalImprovement,
  completeRetrospectiveGoal,
  createGoal,
  getGoal,
  getGoalOverview,
  listGoalImprovements,
  listGoalTickets,
  listGoals,
  pauseGoal,
  rejectGoalImprovement,
  resetGoal,
  resumeGoal,
  startExecutionGoal,
  startPlanningGoal,
  startRetrospectiveGoal,
  updateGoal,
} from "../../core";

export const goalApi = {
  list: listGoals,
  get: getGoal,
  overview: getGoalOverview,
  create: createGoal,
  update: updateGoal,
  startPlanning: startPlanningGoal,
  startExecution: startExecutionGoal,
  startRetrospective: startRetrospectiveGoal,
  completeRetrospective: completeRetrospectiveGoal,
  analyseRetrospective: analyseGoalRetrospective,
  improvements: {
    list: listGoalImprovements,
    approve: approveGoalImprovement,
    reject: rejectGoalImprovement,
    apply: applyGoalImprovement,
  },
  pause: pauseGoal,
  resume: resumeGoal,
  cancel: cancelGoal,
  reset: resetGoal,
  tickets: {
    list: listGoalTickets,
  },
};
